name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # nötig damit der Packager GitHub Releases erstellen darf

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # für korrekte Changelog-Generierung aus Git-History

      - name: Package and release
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY:     ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH:   ${{ secrets.GITHUB_TOKEN }}
